version: '3'
services:
  app:
    build: .
    volumes:
      - .:/workspace:cached
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gsheet
    ports:
      - "5432:5432"
